#! .goreleaser.yaml
changelog:
  sort: asc
  use: github
  filters:
    include:
      - '^.*#[[:digit:]]+.*$'
  groups:
    - title: ⚠️ Breaking Changes
      regexp: '^[[:xdigit:]]+: [[:lower:]]+(\(.*\))?!:.*$'
      order: 1
    - title: 🚀 New Features
      regexp: '^[[:xdigit:]]+: feat(\(.*\))?:.*$'
      order: 2
    - title: 🐛 Bug Fixes
      regexp: '^[[:xdigit:]]+: fix(\(.*\))?:.*$'
      order: 3
    - title: 📖 Docs
      regexp: '^[[:xdigit:]]+: docs(\(.*\))?:.*$'
      order: 4
    - title: 🤖 Bumps
      regexp: '^[[:xdigit:]]+: (gomod|build)\(deps\):.*$'
      order: 5
    - title: 🐒 Miscellaneous
      order: 999

release:
  github:
    owner: unikraft
    name: kraftkit
  draft: false
  prerelease: false
  mode: replace
  header: |
    ## KraftKit {{ .Tag }} ({{ .Date }})

    This is a stable release of kraftkit.
  name_template: 'v{{ .Version }}'

nfpms:
  - vendor: Unikraft
    id: nfpm-default
    maintainer: Alexander Jung <alex@unikraft.io>
    description: Build and use highly customized and ultra-lightweight unikernels.
    license: BSD 3-clause
    bindir: /usr/local/bin
    homepage: https://kraftkit.sh
    formats:
      - deb
      - rpm
      - apk
    recommends:
      - bison
      - build-essential
      - flex
      - git
      - libncurses-dev
      - qemu-system
      - socat
      - unzip
      - wget
    suggests:
      - gcc-x86-64-linux-gnu
      - g++-x86-64-linux-gnu
publishers:
  - name: fury.io
    ids:
      - nfpm-default
    dir: "{{ dir .ArtifactPath }}"
    cmd: curl -F package=@{{ .ArtifactName }} https://{{ .Env.FURY_TOKEN }}@push.fury.io/{{ .Env.FURY_USER }}/
aurs:
  - homepage: https://kraftkit.sh
    ids:
#@ targets = [
#@   "linux-amd64",
#@   "linux-arm64"
#@ ]
#@ for binary in ["kraft"]:
#@ for target in targets:
      - #@ "archive-{}-{}".format(binary, target)
#@ end
#@ end
    description: Build and use highly customized and ultra-lightweight unikernels
    maintainers:
      - "Alexander Jung <alex at unikraft dot io>"
    license: "BSD-3-Clause"
    private_key: "{{ .Env.AUR_KEY }}"
    git_url: "ssh://aur@aur.archlinux.org/kraftkit-bin.git"
    package: |-
      # bin
      install -Dm755 "${srcdir}/kraft" "${pkgdir}/usr/bin/kraft"
      # license
      install -Dm644 "${srcdir}/LICENSE.md" "${pkgdir}/usr/share/licenses/kraftkit/LICENSE"
    commit_author:
      name: Unikraft Bot
      email: monkey+aur@unikraft.io
nix:
  - name: kraftkit
    ids:
#@ targets = [
#@   "linux-amd64",
#@   "linux-arm64"
#@ ]
#@ for binary in ["kraft"]:
#@ for target in targets:
      - #@ "archive-{}-{}".format(binary, target)
#@ end
#@ end
    repository:
      owner: unikraft
      name: nur
    homepage: https://kraftkit.sh
    description: Build and use highly customized and ultra-lightweight unikernels
    path: pkgs/kraftkit/default.nix
    license: BSD-3-Clause
    install: |-
      mkdir -p $out/bin
      cp -vr ./dist/kraft $out/bin/kraft

builds:
#@ targets = {
#@   "linux-amd64": {"os": "linux", "arch": "amd64"},
#@   "linux-arm64": {"os": "linux", "arch": "arm64"},
#@   "freebsd-amd64": {"os": "freebsd", "arch": "amd64"},
#@   "freebsd-arm64": {"os": "freebsd", "arch": "arm64"},
#@   "darwin-arm64": {"os": "darwin", "arch": "arm64"},
#@   "darwin-amd64": {"os": "darwin", "arch": "amd64"}
#@ }
#@ for binary in ["kraft"]:
#@ for target, specs in targets.items():
  - id: #@ "{}-{}".format(binary, target)
    binary: #@ binary
    main: #@ "./cmd/{}".format(binary)
    env:
      - CGO_ENABLED=0
      - GOMOD=kraftkit.sh
    goos:
      - #@ specs["os"]
    goarch:
      - #@ specs["arch"]
    ldflags:
      - -s -w
      - -X {{ .Env.GOMOD }}/internal/version.version={{ .Version }}
      - -X {{ .Env.GOMOD }}/internal/version.commit={{ .Commit }}
      - -X {{ .Env.GOMOD }}/internal/version.buildTime={{ .Date }}
#@ end
#@ end
#@ targets = {
#@   "linux-amd64": {"os": "linux", "arch": "amd64"}
#@ }
#@ for binary in ["runu"]:
#@ for target, specs in targets.items():
  - id: #@ "{}-{}".format(binary, target)
    binary: #@ binary
    main: #@ "./cmd/{}".format(binary)
    env:
      - CGO_ENABLED=1
    goos:
      - #@ specs["os"]
    goarch:
      - #@ specs["arch"]
    ldflags:
      - -s -w
#@ end
#@ end

archives:
#@ targets = [
#@   "linux-amd64",
#@   "linux-arm64",
#@   "freebsd-amd64",
#@   "freebsd-arm64",
#@   "darwin-arm64",
#@   "darwin-amd64"
#@ ]
#@ for binary in ["kraft"]:
#@ for target in targets:
  - id: #@ "archive-{}-{}".format(binary, target)
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    builds:
      - #@ "{}-{}".format(binary, target)
#@ end
#@ end
#@ targets = [
#@   "linux-amd64"
#@ ]
#@ for binary in ["runu"]:
#@ for target in targets:
  - id: #@ "archive-{}-{}".format(binary, target)
    format: tar.gz
    name_template: "{{ .ProjectName }}_runu_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    builds:
      - #@ "{}-{}".format(binary, target)
#@ end
#@ end
