#! .goreleaser.yaml
changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^.*#[[:digit:]]+.*$'
  groups:
    - title: ⚠️ Breaking Changes
      regexp: '^[[:xdigit:]]{7}: [[:lower:]]+(\(.*\))?!:.*$'
      order: 1
    - title: 🚀 New Features
      regexp: '^[[:xdigit:]]{7}: feat(\(.*\))?:.*$'
      order: 2
    - title: 🐛 Bug Fixes
      regexp: '^[[:xdigit:]]{7}: fix(\(.*\))?:.*$'
      order: 3
    - title: 📖 Docs
      regexp: '^[[:xdigit:]]{7}: docs(\(.*\))?:.*$'
      order: 4
    - title: 🤖 Bumps
      regexp: '^[[:xdigit:]]{7}: (gomod|build)\(deps\):.*$'
      order: 5
    - title: 🐒 Miscellaneous
      order: 999

release:
  github:
    owner: unikraft
    name: kraftkit
  draft: false
  prerelease: true
  mode: replace
  header: |
    ## KraftKit {{ .Tag }} ({{ .Date }})

    This is the pre-release version of KraftKit.
  name_template: 'v{{ .Version }}'

nfpms:
  - vendor: Unikraft
    maintainer: Alexander Jung <alex@unikraft.io>
    description: Build and use highly customized and ultra-lightweight unikernels.
    license: BSD 3-clause
    bindir: /usr/local/bin
    homepage: https://kraftkit.sh
    formats:
      - deb
      - rpm
      - apk

builds:
#@ targets = {
#@   "linux-amd64": {"os": "linux", "arch": "amd64"},
#@   "linux-arm64": {"os": "linux", "arch": "arm64"},
#@   "darwin-arm64": {"os": "darwin", "arch": "arm64"},
#@   "darwin-amd64": {"os": "darwin", "arch": "amd64"}
#@ }
#@ for binary in ["kraft"]:
#@ for target, specs in targets.items():
  - id: #@ "{}-{}".format(binary, target)
    binary: #@ binary
    main: #@ "./cmd/{}".format(binary)
    env:
      - CGO_ENABLED=0
      - GOMOD=kraftkit.sh
    goos:
      - #@ specs["os"]
    goarch:
      - #@ specs["arch"]
    ldflags:
      - -s -w
      - -X {{ .Env.GOMOD }}/internal/version.version={{ .Version }}
      - -X {{ .Env.GOMOD }}/internal/version.commit={{ .Commit }}
      - -X {{ .Env.GOMOD }}/internal/version.buildTime={{ .Date }}
#@ end
#@ end
