name: build

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [staging]
    paths:
      - '**'
      - '!.github/**'
      - '.github/workflows/build.yaml'

jobs:
  build:
    runs-on: ubuntu-latest
    container: kraftkit.sh/myself-full:latest
    name: Build Check
    env:
      RUNGOGENERATE: false
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: actions/setup-go@v4
        with:
          go-version: 1.20.2
          cache: false

      - name: Go caches
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ github.job }}-${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ github.job }}-${{ runner.os }}-go-

      - name: Build KraftKit
        run: |
          set -x
          git config --global --add safe.directory /__w/kraftkit/kraftkit
          make kraft

      - name: Run Help Message
        run: |
          set -x
          ./dist/kraft -h
