name: tools/go-generate-qemu-device

on:
  push:
    branches: [staging]
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [staging]
    paths:
      - 'tools/go-generate-qemu-devices/**'
      - '.github/workflows/gobuild-qemu-devices.yaml'

jobs:
  build-qemu-devices:
    runs-on: ubuntu-latest
    container: kraftkit.sh/myself-full:latest
    name: Build Check
    env:
      RUNGOGENERATE: false
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: actions/setup-go@v4
        with:
          go-version: 1.20.2
          cache: false

      - name: Set Go variables
        id: goenv
        run: |
          cd tools/go-generate-qemu-devices
          {
            echo "cache=$(go env GOCACHE)"
            echo "modcache=$(go env GOMODCACHE)"
            echo "mod=$(go env GOMOD)"
          } >>"$GITHUB_OUTPUT"

      - name: Go caches
        uses: actions/cache@v3
        with:
          path: |
            ${{ steps.goenv.outputs.cache }}
            ${{ steps.goenv.outputs.modcache }}
          key: ${{ github.job }}-${{ runner.os }}-go-${{ hashFiles(steps.goenv.outputs.mod) }}
          restore-keys: |
            ${{ github.job }}-${{ runner.os }}-go-

      - name: Build go-generate-qemu-devices
        run: |
          set -x
          git config --global --add safe.directory /__w/kraftkit/kraftkit
          cd tools/go-generate-qemu-devices
          go build -o ../../dist/

      - name: Run Help Message
        run: |
          set -x
          ./dist/go-generate-qemu-devices -h
