name: release-stable

on:
  push:
    tags: ["v[1-9]+.[0-9]+.[0-9]+"]
    branches: [stable]

permissions:
  contents: write
  packages: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    container: kraftkit.sh/myself-full:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Fetch all tags
        run: |
          git config --global --add safe.directory /__w/kraftkit/kraftkit
          git fetch --force --tags

      - name: Generate GoReleaser configuration
        run: |
          ytt -f .goreleaser-stable.yaml > goreleaser-stable.yaml
      - name: Run GoReleaser
        run: |
          echo "$GOOGLE_APPLICATION_JSON" > /tmp/gs.json
          goreleaser build \
            --config goreleaser-stable.yaml \
            --skip-validate
          goreleaser release \
            --config goreleaser-stable.yaml \
            --rm-dist \
            --skip-validate
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          FURY_TOKEN: ${{ secrets.FURY_TOKEN }}
          FURY_USER: ${{ secrets.FURY_USER }}
          AUR_KEY: ${{ secrets.AUR_KEY }}
